sonar.projectKey=mateusz-klatt_snapper-ios
sonar.organization=mateusz-klatt

sonar.host.url=https://sonarcloud.io

sonar.sources=.
sonar.tests=.
sonar.test.inclusions=SnapperTests/**,SnapperUITests/**

sonar.coverageReportPaths=build/sonarqube-generic-coverage.xml

sonar.sourceEncoding=UTF-8
