"""Generate INDEX.md for proprietary/screenshots/ios/ — a markdown gallery
that previews every screen per country code.

Usage:
    python3 build-screenshot-index.py <screenshots-root>

Layout consumed:
    <screenshots-root>/
        <country>/
            <screen>.png

The generated INDEX.md is laid out as one section per country, with a
4-column grid of PNG embeds (markdown image syntax with relative paths).
"""
import sys
from pathlib import Path


SCREEN_ORDER = ["login", "home", "positions", "orders", "alerts", "settings"]


def flag_for(country: str) -> str:
    """Build a Unicode regional-indicator flag emoji from a 2-letter
    country code. ``is`` -> 🇮🇸, ``in`` -> 🇮🇳, ``us`` -> 🇺🇸.
    Returns an empty string for codes that aren't exactly 2 ASCII letters.
    """
    if len(country) != 2 or not country.isalpha():
        return ""
    base = 0x1F1E6
    return "".join(chr(base + ord(c) - ord("a")) for c in country.lower())


def main() -> int:
    if len(sys.argv) != 2:
        print("usage: build-screenshot-index.py <screenshots-root>", file=sys.stderr)
        return 2

    root = Path(sys.argv[1]).resolve()
    if not root.is_dir():
        print(f"error: directory not found: {root}", file=sys.stderr)
        return 1

    countries = sorted(p.name for p in root.iterdir() if p.is_dir())
    if not countries:
        print(f"warning: no country dirs under {root}", file=sys.stderr)

    lines = [
        "# iOS i18n Screenshots",
        "",
        f"Auto-generated by `ios/scripts/build-screenshot-index.py`. Captures "
        f"the SnapperUITests screenshot harness output across {len(countries)} "
        "AppLocale country codes (login + 5 main tabs each).",
        "",
        "Regenerate with:",
        "",
        "```bash",
        "ios/scripts/screenshot-all-locales.sh all",
        "```",
        "",
        "## Countries",
        "",
    ]

    for country in countries:
        country_dir = root / country
        flag = flag_for(country)
        header = f"### {flag} `{country}`" if flag else f"### `{country}`"
        lines.append(header)
        lines.append("")

        present = {p.stem: p for p in country_dir.glob("*.png")}
        ordered = [s for s in SCREEN_ORDER if s in present]
        extras = sorted(s for s in present if s not in SCREEN_ORDER)
        screens = ordered + extras

        if not screens:
            lines.append("_no screenshots_")
            lines.append("")
            continue

        lines.append("| " + " | ".join(screens) + " |")
        lines.append("| " + " | ".join("---" for _ in screens) + " |")
        cells = [f"![{country}/{s}]({country}/{s}.png)" for s in screens]
        lines.append("| " + " | ".join(cells) + " |")
        lines.append("")

    out_path = root / "INDEX.md"
    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"  wrote {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
